# Generated by Django 4.2.2 on 2023-06-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='staus',
            new_name='status',
        ),
    ]
